#!/usr/bin/env bash
# Install nginx in localserver

apt-get -y update
apt-get -y install nginx
sudi ufd allow 'nginx HTTP'
sudo echo 'Hello Worldi!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
