#!/usr/bin/env bash
# Script that redirecting to another page
sudo apt update
sudo apt -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i '/^\tserver_name.*/a \\trewrite ^\/redirect_me/$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;'	/etc/nginx/sites-available/default
sudo service nginx restart
