#!/usr/bin/env bash
# error 404 fix

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.google.com permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/h404.html
sed -i '/listen 80 default_server/a error_page 404 /404_error.html;\nlocation = /404_error.html {\n\troot /var/www/html;\n\tinternal;\n}' /etc/nginx/sites-available/default
service nginx restart
