#!/usr/bin/env bash
# Install Nginx with server 0x01 config
# and add HTTP header named X-Served-By $HOSTNAME

apt-get update
apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello World" | sudo tee file /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo sed -i '/server_name _;/a rewrite ^/redirect_me/ https://www.google.com permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee file /var/www/html/404_error.html
sudo sed -i "/server_name _;/a error_page 404 /404_error.html;\nlocation = /404_error.html {\nroot /var/www/html;\ninternal;\n}" /etc/nginx/sites-available/default
sudo service nginx restart
