#!/usr/bin/env bash
# Install Nginx with server 0x01 config
# and add HTTP header named X-Served-By $HOSTNAME

apt-get update
apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404_error.html > /dev/null

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.google.com;
    }
    error_page 404 /404_error.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
