#!/usr/bin/env bash
# Script that install and configure HAproxi loadblancer
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
printf "\n\nfrontend mati-lop.tech\n\tbind *:80\n\tmode http\n\tdefault_backend web_servers\n\nbackend web_servers\n\tbalance roundrobin\n\tserver 3958-web-01 34.138.32.240:80\n\tserver 3959-web-02 54.82.60.90:80" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
